spring:
    application:
        name: sunny-config-server
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: root
        password: 123456
    sql:
        init:
            schema-locations: classpath:db.sql
            mode: always
    h2:
        console:
            enabled: true
            path: /h2
            settings:
                web-allow-others: true
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
    port: 9129